backend:
  base_url: "http://172.24.208.1:1234/v1"
  base_url2: "https://api.anthropic.com"
  timeout: 120
  verify_ssl: false

listen:
  host: "0.0.0.0"
  port: 8080

ui:
  prefix: "/_ui"

logging:
  level: "DEBUG"
  quiet: false
